### ISSUE TITLE
Error when trying to save empty SDL

### ISSUE THREAD

**Issue by corysturtevant** [akash-network/console-old#94]
**Describe the bug**
Error when trying to save empty SDL

**To Reproduce**
1. Go to https://console.akash.network/new-deployment
2. Click on 'Custom SDL"
3. Click 'Save and Close'
`Compiled with problems:
×
ERROR
Cannot read properties of null (reading 'deployment')
TypeError: Cannot read properties of null (reading 'deployment')
    at transformSdl (https://console.akash.network/static/js/src__helpers_helpers_ts-src_pages_PreflightCheck_tsx-src_pages_SelectProvider_tsx.chunk.js:264:72)
    at CustomApp (https://console.akash.network/static/js/src_pages_CustomApp_tsx.chunk.js:184:76)
    at renderWithHooks (https://console.akash.network/static/js/bundle.js:242032:22)
    at updateFunctionComponent (https://console.akash.network/static/js/bundle.js:244914:24)
    at mountLazyComponent (https://console.akash.network/static/js/bundle.js:245223:21)
    at beginWork (https://console.akash.network/static/js/bundle.js:246619:20)
    at HTMLUnknownElement.callCallback (https://console.akash.network/static/js/bundle.js:231624:18)
    at Object.invokeGuardedCallbackDev (https://console.akash.network/static/js/bundle.js:231668:20)
    at invokeGuardedCallback (https://console.akash.network/static/js/bundle.js:231725:35)
    at beginWork$1 (https://console.akash.network/static/js/bundle.js:251599:11)
ERROR
Cannot read properties of null (reading 'deployment')
TypeError: Cannot read properties of null (reading 'deployment')
    at transformSdl (https://console.akash.network/static/js/src__helpers_helpers_ts-src_pages_PreflightCheck_tsx-src_pages_SelectProvider_tsx.chunk.js:264:72)
    at CustomApp (https://console.akash.network/static/js/src_pages_CustomApp_tsx.chunk.js:184:76)
    at renderWithHooks (https://console.akash.network/static/js/bundle.js:242032:22)
    at updateFunctionComponent (https://console.akash.network/static/js/bundle.js:244914:24)
    at mountLazyComponent (https://console.akash.network/static/js/bundle.js:245223:21)
    at beginWork (https://console.akash.network/static/js/bundle.js:246619:20)
    at HTMLUnknownElement.callCallback (https://console.akash.network/static/js/bundle.js:231624:18)
    at Object.invokeGuardedCallbackDev (https://console.akash.network/static/js/bundle.js:231668:20)
    at invokeGuardedCallback (https://console.akash.network/static/js/bundle.js:231725:35)
    at beginWork$1 (https://console.akash.network/static/js/bundle.js:251599:11)
ERROR
Cannot read properties of null (reading 'deployment')
TypeError: Cannot read properties of null (reading 'deployment')
    at transformSdl (https://console.akash.network/static/js/src__helpers_helpers_ts-src_pages_PreflightCheck_tsx-src_pages_SelectProvider_tsx.chunk.js:264:72)
    at CustomApp (https://console.akash.network/static/js/src_pages_CustomApp_tsx.chunk.js:184:76)
    at renderWithHooks (https://console.akash.network/static/js/bundle.js:242032:22)
    at updateFunctionComponent (https://console.akash.network/static/js/bundle.js:244914:24)
    at mountLazyComponent (https://console.akash.network/static/js/bundle.js:245223:21)
    at beginWork (https://console.akash.network/static/js/bundle.js:246619:20)
    at beginWork$1 (https://console.akash.network/static/js/bundle.js:251577:18)
    at performUnitOfWork (https://console.akash.network/static/js/bundle.js:250846:16)
    at workLoopSync (https://console.akash.network/static/js/bundle.js:250769:9)
    at renderRootSync (https://console.akash.network/static/js/bundle.js:250742:11)`

**Expected behavior**
Pop up saying SDL did not pass check or is empty

**Screenshots**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/52010533/228357809-1e412558-835c-4c4c-9b49-9a4e9fd4fac3.png">

https://user-images.githubusercontent.com/52010533/228358126-298fd35c-7fe8-4ea1-b9a8-9a01b32b9475.mp4

**Desktop (please complete the following information):**
 OS: macOS 13.2.1 (22D68)
Browser Chrome, Brave
Version Brave v1.49.132

**Additional context**

**Comment by yshsaxena** [comment]
Hi @corysturtevan, can you please assign it to me?

**Comment by anilmurty** [comment]
@yshsaxena - it's yours now (thanks for volunteering to fix this!)

**Comment by yshsaxena** [comment]
hi @anilmurty, thanks for assigning it to me!!, We can solve this issue in two ways, first is that we can handle null values on "Save&Close" click, but there we are using a helper function which is having many dependencies throughout the project and personally I do not want to make any changes to that code.

https://github.com/akash-network/console/blob/e4766fb060c887c95ad858abf40abd6ee5d77f4c/web/src/_helpers/helpers.ts#L87-L100

Second, That we can handle this issue in editor itself by hiding/Showing "Save & Close" button, in that way we can force user to close the editor if he hadn't made any changes. And this issue can be solved without affecting any other components.


https://user-images.githubusercontent.com/45199433/229274037-3e1ab8c8-4090-4436-a70b-acbc0d8f6d63.mp4

**Comment by anilmurty** [comment]
Thanks @yshsaxena -  I lean towards the second one for a quicker fix (and it makes sense generally to do that, even if this issue didn't exist) but tagging @jtary for his thoughts as well

**Comment by jtary** [comment]
@yshsaxena I agree with @anilmurty that that second approach would be my preference; though, if you don't mind, I would also see it as a good idea to fix the type of the argument to `transformSdl`. Getting rid of the `sdl: any` would have made this a build-time error instead of run-time. There is an `SDLSpec` interface which implements the correct structure (I think).

**Comment by yshsaxena** [comment]
Hi @anilmurty and @jtary,  Thanks for the Feedback, I tried what @jtary has suggested, PFB the outcome:

![Screenshot 2023-04-04 114104](https://user-images.githubusercontent.com/45199433/229703349-faadfcc6-c2f5-4909-be62-de30864e0f10.png)

![Screenshot 2023-04-04 114133](https://user-images.githubusercontent.com/45199433/229703362-55596103-71c7-45c7-aa34-d4a58e74ada2.png)

any thoughts?

**Comment by jtary** [comment]
Hey @yshsaxena,

I just added a new function to the repo called `isSDLSpec`, you can use this check the type which will satisfy typescript. The checks should look like this:

```
const transformed = transformSdl(configuration)
if (isSDLSpec(transformed)) {
  setFieldValue('sdl', transformed)
}
```

Let me know if you run any more issues 👋

**Comment by jtary** [comment]
Hey @yshsaxena,

I just added a new function to the repo called isSDLSpec, you can use this check the type which will satisfy typescript. The checks should look like this:

```
if (isSDLSpec(configuration)) {
  setFieldValue('sdl', transformSdl(configuration))
} else {
  // handle the error case
}
```

Let me know if you run any more issues 👋

**Comment by yshsaxena** [comment]
Hi @jtary, I tried to implement what you have suggested!!, but now, I m not sure what to do next. can you please review the changes once, present in above commit. and let me know if I am going in the right direction or not!

**Comment by yshsaxena** [comment]
Hi @anilmurty, This is what I have came up now, Completed required checks for SDL using @jtary's new method!!

https://user-images.githubusercontent.com/45199433/230452753-c1567356-5fd0-4790-9634-b7be1ad750ad.mp4

Now, If user any how save the invalid or empty SDL the popup window will not be close automatically, User must have to enter a valid SDL to continue the Deployment.

**Comment by anilmurty** [comment]
Wow! - this is really cool and the first step towards more advanced SDL validation (been on my list to write up requirements for that). Looks good to me to raise a PR with the changes. Thanks so much @yshsaxena !

**Comment by anilmurty** [comment]
by the way - we usually bunch up and push updates to our staging server (user auth restricted) for test before pushing to prod (no user auth). I can share the auth for staging with you if you share your email or drop me a note at anil [at] akash.network
